
package com.infosharesystems.healthcare.telemed.common.constants;

public interface ErrorCodes {

	String GENERIC_EXCEPTION = "GENERIC_EXCEPTION";
	String EXISTING_USER_EXCEPTION = "EXISTING_USER_EXCEPTION";
	String AUTHENTICATION_FAILED_EXCEPTION = "AUTHENTICATION_FAILED_EXCEPTION";
	String EMAIL_NOT_SENT_EXCEPTION = "EMAIL_NOT_SENT_EXCEPTION";
	String USER_NOT_FOUND_EXCEPTION = "USER_NOT_FOUND_EXCEPTION";
	String USER_CREATION_FAILED_EXCEPTION = "USER_CREATION_FAILED_EXCEPTION;";
	String INPUT_VALIDATION_EXCEPTION = "INPUT_VALIDATION_EXCEPTION";
	String LOGIN_FAILED_EXCEPTION = "LOGIN_FAILED_EXCEPTION";
	String REGISTRATION_FAILED_EXCEPTION = "REGISTRATION_FAILED_EXCEPTION";
	String FORGOTPASSWORD_TOKEN_EXPIRED_EXCEPTION = "FORGOT_PASSWORD_TOKEN_EXPIRED_EXCEPTION";
	String VERIFICATION_TOKEN_CREATION_EXCEPTION = "VERIFICATION_TOKEN_CREATION_EXCEPTION";

	String EXISTING_PATIENT_EXCEPTION = "EXISTING_PATIENT_EXCEPTION";
	String PATIENT_NOT_FOUND_EXCEPTION = "PATIENT_NOT_FOUND_EXCEPTION";
	String PATIENT_CREATION_FAILED_EXCEPTION = "PATIENT_CREATION_FAILED_EXCEPTION";

	String EXISTING_VITAL_DEVICE_EXCEPTION = "EXISTING_VITAL_DEVICE_EXCEPTION";
	String VITAL_DEVICE_NOT_FOUND_EXCEPTION = "VITAL_DEVICE_NOT_FOUND_EXCEPTION";
	String VITAL_DEVICE_CREATION_FAILED_EXCEPTION = "VITAL_DEVICE_CREATION_FAILED_EXCEPTION";

	String PHYSICIAN_NOT_FOUND_EXCEPTION = "PHYSICIAN_NOT_FOUND_EXCEPTION";
	String PATIENT_STATUS_UPDATE_EXCEPTION = "PATIENT_STATUS_UPDATE_EXCEPTION";
	String PATIENT_SEARCH_FAILED_EXCEPTION = "PATIENT_SEARCH_FAILED_EXCEPTION";
}
